import localFont from "next/font/local";

import NewHeader from "@/components/UI/NewHeader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProjectsLayout({ children }) {
  return (
    <div>
      <NewHeader />
      <main>{children}</main>
    </div>
  );
}
