
import localFont from "next/font/local";
import "./globals.css";
import MainHeader from "./components/MainHeader/main-header";
import AlignmentContainer from "./components/UI/AlignmentContainer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charset={"UTF-8"} />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>React App</title>
        <link
          href="https://fonts.googleapis.com/css2?family=Kanit:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <AlignmentContainer>{children}</AlignmentContainer>
        <div id="modal"></div>
      </body>
    </html>
  );
}
